services:
  web:
    build: 
      context: .
      target: development
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - HOST=0.0.0.0
      - WDS_SOCKET_HOST=127.0.0.1
      - WDS_SOCKET_PORT=3000
      - REACT_APP_ENV=development
    restart: always
    stdin_open: true
    tty: true
